import {MonthProps} from "./Month.js";

export const months: MonthProps[] = [
    {
        month: 'Dezember 2020',
        expenses: 29.91,
        costs: -5.16,
        acquired: 72.88,
        donations: ["Emperor, Teshaz, Marvin, Thommy, Nameless"],
    },
    {
        month: 'Januar 2021',
        expenses: 266.75,
        costs: 48.69,
        acquired: 84.11,
        donations: [],
    },
    {
        month: 'Februar 2021',
        expenses: 0,
        costs: 48.69,
        acquired: 44,
        donations: [],
    },
    {
        month: 'März 2021',
        expenses: 0,
        costs: 48.69,
        acquired: 45,
        donations: [],
    },
    {
        month: 'April 2021',
        expenses: 0,
        costs: 48.69,
        acquired: 76,
        donations: [],
    },
    {
        month: 'Mai 2021',
        expenses: 264,
        costs: 48.69,
        acquired: 30,
        donations: [],
    },
    {
        month: 'Juni 2021',
        expenses: 0,
        costs: 49.22,
        acquired: 46,
        donations: [],
    },
    {
        month: 'Juli 2021',
        expenses: 0,
        costs: 49.22,
        acquired: 25,
        donations: [],
    },
    {
        month: 'August 2021',
        expenses: 0,
        costs: 49.22,
        acquired: 30,
        donations: [],
    },
    {
        month: 'September 2021',
        expenses: 0,
        costs: 49.22,
        acquired: 49.11,
        donations: [],
    },
    {
        month: 'Oktober 2021',
        expenses: 6.60,
        costs: 49.22,
        acquired: 125,
        donations: [],
    },
    {
        month: 'November 2021',
        expenses: 411.63,
        costs: 56.87,
        acquired: 112.97,
        donations: [],
    },
    {
        month: 'Dezember 2021',
        expenses: 0,
        costs: 56.87,
        acquired: 36.35,
        donations: [],
    },
    {
        month: 'Januar 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 62,
        donations: [],
    },
    {
        month: 'Februar 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 55,
        donations: [],
    },
    {
        month: 'März 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 25,
        donations: [],
    },
    {
        month: 'April 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 70,
        donations: [],
    },
    {
        month: 'Mai 2022',
        expenses: 263.97,
        costs: 56.87,
        acquired: 30,
        donations: [],
    },
    {
        month: 'Juni 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 80.55,
        donations: [],
    },
    {
        month: 'Juli 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 54.83,
        donations: [],
    },
    {
        month: 'August 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 29,
        donations: [],
    },
    {
        month: 'September 2022',
        expenses: 0,
        costs: 56.87,
        acquired: 20,
        donations: [],
    },
    {
        month: 'Oktober 2022',
        expenses: 6.59,
        costs: 56.87,
        acquired: 87.83,
        donations: [],
    },
    {
        month: 'November 2022',
        expenses: 330.22,
        costs: 53.77,
        acquired: 128.58,
        donations: [],
    },
    {
        month: 'Dezember 2022',
        expenses: 32.84,
        costs: 79.27,
        acquired: 229.08,
        donations: [],
    },
    {
        month: 'Januar 2023',
        expenses: 32.84,
        costs: 79.27,
        acquired: 37.77,
        donations: [],
    },
    {
        month: 'Februar 2023',
        expenses: 32.84,
        costs: 79.27,
        acquired: 55,
        donations: [],
    },
    {
        month: 'März 2023',
        expenses: 32.84,
        costs: 79.27,
        acquired: 15,
        donations: [],
    },
    {
        month: 'April 2023',
        expenses: 32.84,
        costs: 79.27,
        acquired: 10,
        donations: [],
    },
    {
        month: 'Mai 2023',
        expenses: 32.84,
        costs: 35.28,
        acquired: 5,
        donations: [],
    },
    {
        month: 'Juni 2023',
        expenses: 32.84,
        costs: 42.60,
        acquired: 15,
        donations: [],
    },
    {
        month: 'Juli 2023',
        expenses: 32.84,
        costs: 42.60,
        acquired: 5,
        donations: [],
    },
    {
        month: 'August 2023',
        expenses: 32.84,
        costs: 42.60,
        acquired: 5,
        donations: [],
    },
    {
        month: 'September 2023',
        expenses: 32.84,
        costs: 42.60,
        acquired: 5,
        donations: [],
    },
];
